// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"dealership/ent/cars"
	"dealership/ent/dealership"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DealershipCreate is the builder for creating a Dealership entity.
type DealershipCreate struct {
	config
	mutation *DealershipMutation
	hooks    []Hook
}

// SetCity sets the "city" field.
func (dc *DealershipCreate) SetCity(s string) *DealershipCreate {
	dc.mutation.SetCity(s)
	return dc
}

// SetName sets the "name" field.
func (dc *DealershipCreate) SetName(s string) *DealershipCreate {
	dc.mutation.SetName(s)
	return dc
}

// AddCarIDs adds the "cars" edge to the Cars entity by IDs.
func (dc *DealershipCreate) AddCarIDs(ids ...int) *DealershipCreate {
	dc.mutation.AddCarIDs(ids...)
	return dc
}

// AddCars adds the "cars" edges to the Cars entity.
func (dc *DealershipCreate) AddCars(c ...*Cars) *DealershipCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return dc.AddCarIDs(ids...)
}

// Mutation returns the DealershipMutation object of the builder.
func (dc *DealershipCreate) Mutation() *DealershipMutation {
	return dc.mutation
}

// Save creates the Dealership in the database.
func (dc *DealershipCreate) Save(ctx context.Context) (*Dealership, error) {
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DealershipCreate) SaveX(ctx context.Context) *Dealership {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DealershipCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DealershipCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DealershipCreate) check() error {
	if _, ok := dc.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Dealership.city"`)}
	}
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Dealership.name"`)}
	}
	return nil
}

func (dc *DealershipCreate) sqlSave(ctx context.Context) (*Dealership, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DealershipCreate) createSpec() (*Dealership, *sqlgraph.CreateSpec) {
	var (
		_node = &Dealership{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(dealership.Table, sqlgraph.NewFieldSpec(dealership.FieldID, field.TypeInt))
	)
	if value, ok := dc.mutation.City(); ok {
		_spec.SetField(dealership.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.SetField(dealership.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := dc.mutation.CarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dealership.CarsTable,
			Columns: dealership.CarsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cars.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DealershipCreateBulk is the builder for creating many Dealership entities in bulk.
type DealershipCreateBulk struct {
	config
	builders []*DealershipCreate
}

// Save creates the Dealership entities in the database.
func (dcb *DealershipCreateBulk) Save(ctx context.Context) ([]*Dealership, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Dealership, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DealershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DealershipCreateBulk) SaveX(ctx context.Context) []*Dealership {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DealershipCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DealershipCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
