// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (d *Dealership) Cars(ctx context.Context) (result []*Cars, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = d.NamedCars(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = d.Edges.CarsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = d.QueryCars().All(ctx)
	}
	return result, err
}
