apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ${NAMESPACE}
  name: ws-service
  labels:
    app: ws-service
spec:
  replicas: ${REPLICAS}
  serviceName: ws-service
  selector:
    matchLabels:
      app: ws-service
  template:
    metadata:
      labels:
        app: ws-service
    spec:
      imagePullSecrets:
        - name: dockerregistrykey
      containers:
        - image: ${ECR_IMAGE}
          name: ws-service
          imagePullPolicy: Always
          resources: { }
          lifecycle:
            postStart: # same as istio-proxy readiness probe, when this hook exec failed, the app container will be restarted
              httpGet:
                path: /healthz/ready
                port: 15020
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: AUTH_URL
              value: "http://auth:8000"
            - name: SENTRY_DNS
              value: ${SENTRY_DNS}
            - name: ENV
              value: ${ENV}
            - name: BRANCH
              value: ${BRANCH}
            - name: COMMIT
              value: ${COMMIT}
            - name: NATS_SERVERS
              value: "nats://dev-playground-nats:4222"
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ws-service
  labels:
    run: ws-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      name: service
  selector:
    app: ws-service
  type: NodePort
