// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package cars

import (
	"dealership/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Cars {
	return predicate.Cars(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Cars {
	return predicate.Cars(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Cars {
	return predicate.Cars(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Cars {
	return predicate.Cars(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Cars {
	return predicate.Cars(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Cars {
	return predicate.Cars(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Cars {
	return predicate.Cars(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Cars {
	return predicate.Cars(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Cars {
	return predicate.Cars(sql.FieldLTE(FieldID, id))
}

// HasDealershipCars applies the HasEdge predicate on the "dealership_cars" edge.
func HasDealershipCars() predicate.Cars {
	return predicate.Cars(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, DealershipCarsTable, DealershipCarsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDealershipCarsWith applies the HasEdge predicate on the "dealership_cars" edge with a given conditions (other predicates).
func HasDealershipCarsWith(preds ...predicate.Dealership) predicate.Cars {
	return predicate.Cars(func(s *sql.Selector) {
		step := newDealershipCarsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cars) predicate.Cars {
	return predicate.Cars(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cars) predicate.Cars {
	return predicate.Cars(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cars) predicate.Cars {
	return predicate.Cars(func(s *sql.Selector) {
		p(s.Not())
	})
}
