// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cars is the predicate function for cars builders.
type Cars func(*sql.Selector)

// Dealership is the predicate function for dealership builders.
type Dealership func(*sql.Selector)
