// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"car/ent/car"
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// CarEdge is the edge representation of Car.
type CarEdge struct {
	Node   *Car   `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// CarConnection is the connection containing edges to Car.
type CarConnection struct {
	Edges      []*CarEdge `json:"edges"`
	PageInfo   PageInfo   `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

func (c *CarConnection) build(nodes []*Car, pager *carPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Car
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Car {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Car {
			return nodes[i]
		}
	}
	c.Edges = make([]*CarEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &CarEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// CarPaginateOption enables pagination customization.
type CarPaginateOption func(*carPager) error

// WithCarOrder configures pagination ordering.
func WithCarOrder(order *CarOrder) CarPaginateOption {
	if order == nil {
		order = DefaultCarOrder
	}
	o := *order
	return func(pager *carPager) error {
		if err := order.Direction.Validate(); err != nil {
			return err
		}
		if order.Field == nil {
			order.Field = DefaultCarOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithCarFilter configures pagination filter.
func WithCarFilter(filter func(*CarQuery) (*CarQuery, error)) CarPaginateOption {
	return func(pager *carPager) error {
		if filter == nil {
			return errors.New("CarQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type carPager struct {
	reverse bool
	order   *CarOrder
	filter  func(*CarQuery) (*CarQuery, error)
}

func newCarPager(opts []CarPaginateOption, reverse bool) (*carPager, error) {
	pager := &carPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultCarOrder
	}
	return pager, nil
}

func (p *carPager) applyFilter(query *CarQuery) (*CarQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *carPager) toCursor(c *Car) Cursor {
	return p.order.Field.toCursor(c)
}

func (p *carPager) applyCursors(query *CarQuery, after, before *Cursor) (*CarQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultCarOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *carPager) applyOrder(query *CarQuery) *CarQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultCarOrder.Field {
		query = query.Order(DefaultCarOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *carPager) orderExpr(query *CarQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultCarOrder.Field {
			b.Comma().Ident(DefaultCarOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Car.
func (c *CarQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...CarPaginateOption,
) (*CarConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newCarPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if c, err = pager.applyFilter(c); err != nil {
		return nil, err
	}
	conn := &CarConnection{Edges: []*CarEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = c.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if c, err = pager.applyCursors(c, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		c.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := c.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	c = pager.applyOrder(c)
	nodes, err := c.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// CarOrderField defines the ordering field of Car.
type CarOrderField struct {
	// Value extracts the ordering value from the given Car.
	Value    func(*Car) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) car.OrderOption
	toCursor func(*Car) Cursor
}

// CarOrder defines the ordering of Car.
type CarOrder struct {
	Direction OrderDirection `json:"direction"`
	Field     *CarOrderField `json:"field"`
}

// DefaultCarOrder is the default ordering of Car.
var DefaultCarOrder = &CarOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &CarOrderField{
		Value: func(c *Car) (ent.Value, error) {
			return c.ID, nil
		},
		column: car.FieldID,
		toTerm: car.ByID,
		toCursor: func(c *Car) Cursor {
			return Cursor{ID: c.ID}
		},
	},
}

// ToEdge converts Car into CarEdge.
func (c *Car) ToEdge(order *CarOrder) *CarEdge {
	if order == nil {
		order = DefaultCarOrder
	}
	return &CarEdge{
		Node:   c,
		Cursor: order.Field.toCursor(c),
	}
}
