// Copyright 2022-present Vlabs Development Kft
//
// All rights reserved under a proprietary license.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"car/ent/car"
	"car/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	carFields := schema.Car{}.Fields()
	_ = carFields
	// carDescIsSold is the schema descriptor for is_sold field.
	carDescIsSold := carFields[0].Descriptor()
	// car.DefaultIsSold holds the default value on creation for the is_sold field.
	car.DefaultIsSold = carDescIsSold.Default.(bool)
}
